services:
  db:
    image: postgres:16
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env

  redis:
    image: redis:alpine
    container_name: rediscache

  api:
    restart: unless-stopped
    container_name: django-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/api
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  web:
    restart: unless-stopped
    container_name: nextjs-web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: npm run dev
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  postgres_data:
